version: "3.1"
services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - ./nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./public/:/application/public
      - ./logs/:/var/log/nginx/

  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./public:/application/public
      - ./system:/application/system
      - ./application:/application/application
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_task
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - "3306:3306"